# Generated by Django 5.0.6 on 2026-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "オーナー"),
                    ("supporter", "外部支援者"),
                    ("agency_admin", "代理店管理者"),
                ],
                default="owner",
                max_length=20,
                verbose_name="ロール",
            ),
        ),
    ]
