# Generated by Django 5.0.6 on 2026-05-12 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_add_csv_fields"),
        ("stores", "0002_menu_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("new_customer", "新規獲得"),
                            ("repeat", "再来店"),
                            ("first_followup", "初回フォロー"),
                            ("dormant_reactivation", "休眠復帰"),
                            ("upsell", "アップセル"),
                            ("renewal", "更新・回数券"),
                            ("awareness", "認知拡大"),
                            ("custom", "カスタム"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("official_line", "公式LINE"),
                            ("lstep", "Lステップ"),
                            ("instagram", "Instagram"),
                            ("google_business", "Googleビジネス"),
                            ("email", "メール"),
                            ("sms", "SMS"),
                            ("phone", "電話"),
                            ("in_store", "店頭"),
                            ("flyer", "チラシ"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "提案"),
                            ("draft", "下書き"),
                            ("approval_pending", "承認待ち"),
                            ("approved", "承認済み"),
                            ("executed", "実行済み"),
                            ("result_pending", "結果入力待ち"),
                            ("reviewed", "振り返り完了"),
                            ("on_hold", "保留"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("target_count", models.PositiveIntegerField(blank=True, null=True)),
                ("caution_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("line", "LINE"),
                            ("instagram", "Instagram"),
                            ("google_business", "Googleビジネス"),
                            ("email", "メール"),
                            ("pop", "POP"),
                            ("flyer", "チラシ"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                ("cta", models.TextField(blank=True, null=True)),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("polite", "丁寧"),
                            ("friendly", "フレンドリー"),
                            ("professional", "プロフェッショナル"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("generated_by_ai", models.BooleanField(default=False)),
                (
                    "expression_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[("none", "なし"), ("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("expression_check_result", models.JSONField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("approval_pending", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "差戻し"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_contents",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_contents",
            },
        ),
        migrations.CreateModel(
            name="CampaignTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_reason", models.TextField(blank=True, null=True)),
                ("excluded", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "未送信"),
                            ("sent", "送信済み"),
                            ("failed", "失敗"),
                            ("manual_done", "手動実施済み"),
                            ("skipped", "スキップ"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_targets",
                        to="customers.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_targets",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_targets",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["store_id", "status"], name="campaigns_store_i_ca4bfe_idx"),
        ),
        migrations.AddIndex(
            model_name="campaigncontent",
            index=models.Index(
                fields=["store_id", "approval_status"], name="campaign_co_store_i_cd14e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaigntarget",
            index=models.Index(
                fields=["campaign_id", "excluded"], name="campaign_ta_campaig_811793_idx"
            ),
        ),
    ]
