# Generated by Codex on 2026-06-14

from django.db import migrations


def normalize_expression_risk_level(apps, schema_editor):
    CampaignContent = apps.get_model("campaigns", "CampaignContent")
    mappings = {
        "safe": "none",
        "caution": "medium",
        "high_risk": "high",
    }
    for old_value, new_value in mappings.items():
        CampaignContent.objects.filter(expression_risk_level=old_value).update(
            expression_risk_level=new_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaign_result"),
    ]

    operations = [
        migrations.RunPython(normalize_expression_risk_level, migrations.RunPython.noop),
    ]
