# Generated by Django 5.0.6 on 2026-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "ログイン"),
                    ("store_updated", "店舗情報更新"),
                    ("customer_created", "顧客作成"),
                    ("customer_updated", "顧客更新"),
                    ("customer_deleted", "顧客削除"),
                    ("consent_updated", "同意状態更新"),
                    ("unsubscribed", "配信停止"),
                    ("resubscribed", "配信停止解除"),
                    ("csv_uploaded", "CSVアップロード"),
                    ("csv_import_executed", "CSV取込実行"),
                    ("ai_diagnosis_executed", "AI診断実行"),
                    ("line_broadcast_created", "LINE配信作成"),
                    ("line_broadcast_sent", "LINE配信実行"),
                ],
                max_length=50,
            ),
        ),
    ]
