# Generated by Django 5.0.6 on 2026-05-09 21:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_menu_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_customer_id", models.CharField(blank=True, max_length=255, null=True)),
                ("line_user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_contact_date", models.DateField(blank=True, null=True)),
                ("acquisition_channel", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有効"), ("inactive", "無効")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "女性"),
                            ("male", "男性"),
                            ("other", "その他"),
                            ("unknown", "不明"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("age_group", models.CharField(blank=True, max_length=20, null=True)),
                ("residential_area", models.CharField(blank=True, max_length=100, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("preferences", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["store_id"], name="customers_store_i_1480a3_idx"),
        ),
    ]
