# Generated by Django 5.0.6 on 2026-05-10 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("contact_line_allowed", models.BooleanField(default=True)),
                ("contact_email_allowed", models.BooleanField(default=True)),
                ("contact_sms_allowed", models.BooleanField(default=True)),
                ("analysis_allowed", models.BooleanField(default=True)),
                ("external_integration_allowed", models.BooleanField(default=True)),
                ("is_unsubscribed", models.BooleanField(default=False)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("consent_source", models.CharField(blank=True, max_length=100, null=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_consents",
            },
        ),
    ]
