# Generated by Django 5.0.6 on 2026-05-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_add_customer_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="kana",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="first_visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="total_sales",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="visit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
