# Generated by Django 5.0.6 on 2026-05-14 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_menu_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("initial_diagnosis", "初期診断"),
                            ("monthly", "月次レポート"),
                            ("customer_state", "顧客状態"),
                            ("dormant", "休眠分析"),
                            ("campaign_result", "施策結果"),
                            ("lstep_judgement", "Lステップ要否診断"),
                            ("agency_proposal", "代理店提案"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("body_markdown", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("generated_by_ai", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("shared", "共有済み"),
                            ("archived", "アーカイブ"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("contains_personal_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "report_type", "period_start"],
                        name="reports_store_i_4a3c94_idx",
                    ),
                    models.Index(fields=["store", "created_at"], name="reports_store_i_7c6704_idx"),
                ],
            },
        ),
    ]
