# Generated by Django 5.0.6 on 2026-05-10 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_menu_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("customers", "顧客"),
                            ("reservations", "予約/来店"),
                            ("sales", "売上"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("spreadsheet", "スプレッドシート"),
                            ("manual", "手動"),
                            ("api", "API"),
                        ],
                        default="csv",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="imports/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待機中"),
                            ("processing", "処理中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("success_rows", models.IntegerField(blank=True, null=True)),
                ("error_rows", models.IntegerField(blank=True, null=True)),
                ("executed_by", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("row_number", models.IntegerField(blank=True, null=True)),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("missing_required", "必須項目欠損"),
                            ("invalid_format", "フォーマット不正"),
                            ("duplicated", "重複"),
                            ("mapping_error", "マッピングエラー"),
                            ("unknown", "不明"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="imports.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "import_errors",
                "ordering": ["row_number"],
            },
        ),
    ]
