# Generated by Django 5.0.6 on 2026-05-10 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_add_customer_consent"),
        ("reservations", "0001_initial_reservation"),
        ("stores", "0002_menu_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sale_date", models.DateField()),
                ("amount", models.IntegerField()),
                ("item_name_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "item_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("service", "施術・サービス"),
                            ("product", "物販"),
                            ("ticket", "回数券"),
                            ("subscription", "定期契約"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "現金"),
                            ("card", "カード"),
                            ("qr", "QRコード"),
                            ("bank", "銀行振込"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ticket_remaining_count", models.IntegerField(blank=True, null=True)),
                (
                    "contract_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "契約中"),
                            ("ended", "終了"),
                            ("renewal_due", "更新期限近い"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="stores.menu",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "indexes": [
                    models.Index(fields=["store_id", "sale_date"], name="sales_store_i_2f7630_idx"),
                    models.Index(
                        fields=["customer_id", "sale_date"], name="sales_custome_6ea792_idx"
                    ),
                ],
            },
        ),
    ]
