# Generated by Django 5.0.6 on 2026-05-10 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_add_customer_consent"),
        ("stores", "0002_menu_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_reservation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reservation_created_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_start_at", models.DateTimeField()),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                ("visited_at", models.DateTimeField(blank=True, null=True)),
                ("menu_name_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                ("staff_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("official_line", "公式LINE"),
                            ("phone", "電話"),
                            ("hpb", "ホットペッパービューティー"),
                            ("instagram", "Instagram"),
                            ("web", "Webサイト"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "予約済み"),
                            ("visited", "来店済み"),
                            ("cancelled", "キャンセル"),
                            ("no_show", "無断キャンセル"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("has_next_reservation", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="customers.customer",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="stores.menu",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "reservations",
                "indexes": [
                    models.Index(
                        fields=["store_id", "scheduled_start_at"],
                        name="reservation_store_i_08f988_idx",
                    ),
                    models.Index(
                        fields=["customer_id", "scheduled_start_at"],
                        name="reservation_custome_23b146_idx",
                    ),
                ],
            },
        ),
    ]
