# Generated by Django 5.0.6 on 2026-05-13 03:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("purpose", models.CharField(max_length=50)),
                ("channel", models.CharField(max_length=50)),
                ("system_prompt", models.TextField()),
                ("user_prompt_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "indexes": [
                    models.Index(
                        fields=["purpose", "channel", "is_active"],
                        name="ai_prompt_t_purpose_440425_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("template_name", models.CharField(max_length=100)),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("model_used", models.CharField(max_length=100)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "campaign_content",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_log",
                        to="campaigns.campaigncontent",
                    ),
                ),
            ],
            options={
                "db_table": "ai_generation_logs",
                "indexes": [
                    models.Index(
                        fields=["store_id", "created_at"], name="ai_generati_store_i_b4fae4_idx"
                    ),
                    models.Index(fields=["campaign_id"], name="ai_generati_campaig_4a9796_idx"),
                ],
            },
        ),
    ]
