# Generated by Django 5.0.6 on 2026-05-13 13:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIExpressionCheckLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("content_type", models.CharField(max_length=30)),
                ("industry", models.CharField(max_length=50)),
                ("body_length", models.PositiveIntegerField()),
                ("risk_level", models.CharField(max_length=20)),
                ("risk_score", models.PositiveIntegerField()),
                ("issues_count", models.PositiveIntegerField()),
                ("model_used", models.CharField(max_length=100)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_expression_check_logs",
                "indexes": [
                    models.Index(
                        fields=["store_id", "created_at"], name="ai_expressi_store_i_b379cb_idx"
                    )
                ],
            },
        ),
    ]
