# Generated by Django 5.0.6 on 2026-05-14 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0002_aiexpressionchecklog"),
        ("campaigns", "0002_campaign_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIImprovementLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("model_used", models.CharField(max_length=100)),
                ("confidence", models.CharField(blank=True, max_length=10, null=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="improvement_logs",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "ai_improvement_logs",
                "indexes": [
                    models.Index(
                        fields=["store_id", "created_at"], name="ai_improvem_store_i_675148_idx"
                    ),
                    models.Index(fields=["campaign_id"], name="ai_improvem_campaig_1c8d89_idx"),
                ],
            },
        ),
    ]
