# Generated by Django 5.0.6 on 2026-05-27 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0003_add_ai_improvement_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyDiagnosisLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("overall_score", models.PositiveIntegerField()),
                ("issues_count", models.PositiveIntegerField()),
                ("model_used", models.CharField(max_length=100)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agency_diagnosis_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_agency_diagnosis_logs",
                "indexes": [
                    models.Index(
                        fields=["store_id", "created_at"], name="ai_agency_d_store_i_e970e7_idx"
                    )
                ],
            },
        ),
    ]
