# Generated by Django 5.0.6 on 2026-05-10 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_add_csv_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("store_id", models.UUIDField()),
                ("insight_date", models.DateField()),
                (
                    "customer_state",
                    models.CharField(
                        choices=[
                            ("new_lead", "新規リード"),
                            ("first_reserved", "初回予約済"),
                            ("after_first_visit", "初回来店後"),
                            ("repeater", "リピーター"),
                            ("pre_dormant", "休眠予備軍"),
                            ("dormant", "休眠顧客"),
                            ("vip_candidate", "VIP候補"),
                            ("high_risk", "離脱リスク高"),
                        ],
                        max_length=30,
                    ),
                ),
                ("inferred_needs", models.JSONField(default=list)),
                ("blocking_factors", models.JSONField(default=list)),
                ("recommended_action", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")], max_length=10
                    ),
                ),
                ("evidence_summary", models.TextField()),
                (
                    "ai_confidence",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")], max_length=10
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "未確認"),
                            ("confirmed", "確認済み"),
                            ("modified", "修正済み"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("created_by_ai", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_insights",
                "indexes": [
                    models.Index(
                        fields=["store_id", "customer_state"], name="customer_in_store_i_3dd532_idx"
                    ),
                    models.Index(
                        fields=["customer_id", "insight_date"],
                        name="customer_in_custome_246148_idx",
                    ),
                ],
            },
        ),
    ]
