# Generated by Django 5.0.6 on 2026-05-09 19:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('esthetic', 'エステ'), ('bodycare', 'ボディケア'), ('gym', 'ジム'), ('nail', 'ネイル'), ('hair', 'ヘアサロン'), ('other', 'その他')], max_length=50)),
                ('sub_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('prefecture', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area_label', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('business_hours', models.JSONField(blank=True, null=True)),
                ('closed_days', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '稼働中'), ('inactive', '停止中')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_goal', models.CharField(blank=True, choices=[('new_customers', '新規獲得'), ('repeat', 'リピート促進'), ('ltv', 'LTV向上'), ('dormant_reactivation', '休眠復帰')], max_length=50, null=True)),
                ('tone', models.CharField(blank=True, choices=[('polite', '丁寧'), ('friendly', 'フレンドリー'), ('professional', 'プロフェッショナル')], max_length=20, null=True)),
                ('ai_suggestion_level', models.CharField(blank=True, choices=[('conservative', '控えめ'), ('standard', '標準'), ('aggressive', '積極的')], max_length=20, null=True)),
                ('require_approval_for_external', models.BooleanField(default=True)),
                ('default_dormant_days', models.IntegerField(blank=True, null=True)),
                ('default_pre_dormant_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'db_table': 'store_settings',
            },
        ),
        migrations.CreateModel(
            name='StoreTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('official_line', '公式LINE'), ('lstep', 'Lステップ'), ('lmessage', 'Lメッセージ'), ('instagram', 'Instagram'), ('google_business', 'Googleビジネス'), ('reservation', '予約システム'), ('pos', 'POS'), ('spreadsheet', 'スプレッドシート')], max_length=50)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_status', models.CharField(choices=[('using', '利用中'), ('considering', '検討中'), ('not_using', '未利用')], max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_status', models.CharField(blank=True, choices=[('not_connected', '未接続'), ('connected', '接続済'), ('error', 'エラー')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='stores.store')),
            ],
            options={
                'db_table': 'store_tools',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant_id'], name='stores_tenant__ee85b2_idx'),
        ),
        migrations.AddIndex(
            model_name='storetool',
            index=models.Index(fields=['store_id'], name='store_tools_store_i_b99f23_idx'),
        ),
    ]
