# Generated by Django 5.0.6 on 2026-05-14 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_menu_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("can_view", models.BooleanField(default=True, verbose_name="閲覧権限")),
                (
                    "can_edit_campaigns",
                    models.BooleanField(default=False, verbose_name="施策編集権限"),
                ),
                (
                    "can_view_personal_info",
                    models.BooleanField(default=False, verbose_name="個人情報閲覧権限"),
                ),
                ("can_export_csv", models.BooleanField(default=False, verbose_name="CSV出力権限")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_collaborators",
                "indexes": [
                    models.Index(fields=["store_id"], name="store_colla_store_i_7b8b0d_idx")
                ],
                "unique_together": {("store", "user")},
            },
        ),
    ]
